### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by erin-koen** [avantgardefinance/interface#341] opened 2020-02-13 19:46 UTC
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x38e925da209ea3eb1707620b2117c54bc5cad7a47565cb2e386c1e230a40e561",
  "blockNumber": 9476643,
  "contractAddress": null,
  "cumulativeGasUsed": 6938924,
  "from": "0x0d947d68f583e8b23ff816df9ff3f23a8cfd7496",
  "gasUsed": 39916,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x4541c374c18365533e5b7d568fd0e26eab6d8635",
  "transactionHash": "0x779eeb7b2b9562eeaa3f96fc6ca75f150d191e0fedb385a54e1ab6e922ebeff7",
  "transactionIndex": 88
}
    at t._next (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:930262)
    at t.__tryOrUnsub (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:65209)
    at t.next (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:64354)
    at t._next (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:63430)
    at t.next (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:63101)
    at e.value (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:921056)
    at https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:919219
    at c (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:1576096)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:1575849)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.a051051f.chunk.js:2:1576453)

**Comment by fubhy** [comment] 2020-02-13 21:02
Duplicate of #337

**Closed by fubhy** 2020-02-13 21:02 UTC
